routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /growing/:
    controller: channel
    filter: tag:[germination,seedling,vegetation,flowering,drying,curing]
  /app/:
    controller: channel
    filter: tag:[app]
  /faqs/:
    controller: channel
    filter: tag:[general]
  /hardward/:
    controller: channel
    filter: tag:[hardward]

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
