routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /growing/:
    controller: channel
      template: index
    filter: tag:[Germination,Seedling,Vegetation,Flowering,Drying,Curing]
    
  /app/:
    controller: channel
      template: index
    filter: tag:[App]
    
  /faqs/:
    controller: channel
       template: index
    filter: tag:[General]
   
  /hardware/:
    controller: channel
      template: index
    filter: tag:[Hardware]

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
