routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /growing/:
    controller: channel
    filter: tag:[Germination,Seedling,Vegetation,Flowering,Drying,Curing]
    template: channel
  /app/:
    controller: channel
    filter: tag:[app]
    template: channel
  /faqs/:
    controller: channel
    filter: tag:[General]
    template: channel
  /hardware/:
    controller: channel
    filter: tag:[Hardware]
    template: channel

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
